# Generated by Django 4.2.3 on 2024-03-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_audiodetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
