# Generated by Django 4.2.3 on 2024-03-30 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0003_alter_audiodetail_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listenlater',
            fields=[
                ('listen_id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_id', models.CharField(default='', max_length=10000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
