# Generated by Django 4.2.3 on 2024-04-14 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0008_rename_date_posted_recentplay_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('trend_id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_id', models.CharField(default='', max_length=10000000)),
                ('count', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
