# Generated by Django 4.2.3 on 2024-04-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_trend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trend',
            old_name='count',
            new_name='count_of_song',
        ),
    ]
